travis: try to fix rvm install error
We currently get the error below:

$ rvm use system --install --binary --fuzzy
curl: (22) The requested URL returned error: 404 Not Found
Now using system ruby.
** Updating RubyGems to the latest compatible version for security reasons. **
** If you need an older version, you can downgrade with 'gem update --system OLD_VERSION'. **
0.58s$ gem install bundler
Fetching: bundler-2.1.4.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.
The command "gem install bundler" failed and exited with 1 during .

Therefore, let's try without specifiying rvm.